### ISSUE TITLE
Distribution: Header file missing

### ISSUE THREAD

**Issue by thtomate** [monofox/python-aqbanking#14]
If I try to to build it in a docker container (based on the python:3.5 container) with all requirement fullfiled, it fails:
```
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include/gwenhywfar4 -I/usr/include/aqbanking5 -I/usr/local/include/gwenhywfar4 -I/usr/local/include/aqbanking5 -I/usr/local/include/python3.5m -c aqbanking/pyaqhandler.cpp -o build/temp.linux-x86_64-3.5/aqbanking/pyaqhandler.o -Wunused-variable -Wunused-function
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    aqbanking/pyaqhandler.cpp:7:27: fatal error: pyaqhandler.hpp: No such file or directory
     #include "pyaqhandler.hpp"
                               ^
```
I suspect (but not tested) this could be solved by adding `aqbanking/` to the include path as stated here: https://docs.python.org/3/distutils/setupscript.html#preprocessor-options

**Comment by monofox** [comment]
@thtomate : could you try it out? Because build job on my system as well as travis is able to compile with python 3.5.
Which gcc version do you use? Which commands did you executed?
Do you use the master branch?
Could post whole build output?
Do you have any custom compiler flags given through environment variables? Because i did not specified anywhere the -Wstrict-prototypes nor -DNDEBUG

**Comment by thtomate** [comment]
It also works on my local machines.
But there is a project, where docker usage for CI is mandatory.
I am doing:
```
$ docker run -it python:3.5 bash
# apt update
# apt install libaqbanking-dev libgwenhywfar60-dev
# pip install python-aqbanking
```
But this is not the problem.
The header file is missing in the package, this can be seen on pypi https://pypi.org/project/python-aqbanking/#files I don't know why.

**Comment by monofox** [comment]
Clear, thank you! I uploaded a new version. Could you please verify that its fine now?

**Comment by thtomate** [comment]
It works now.
