### ISSUE TITLE
Gcc fails on debian with gcc 4.6

### ISSUE THREAD

**Issue by ghost** [monofox/python-aqbanking#4]
Hi!
I've tinkered around with 

```
#extra_compile_args=['-O0', '-g', '-Wunused-variable', '-std=gnu++11', '-DPy_DEBUG', '-Wunused-function', '-DDEBUG'],
extra_compile_args=['-Wunused-variable', '-Wunused-function', '-std=gnu++0x'],

```

but even with that to no result (but it got further than before without gnu++0x.
Can you tell me which compilers you used on which plattform successfully?

I'm running Raspbian GNU Linux 7 

```
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.6/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Debian 4.6.3-14+rpi1' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.6.3 (Debian 4.6.3-14+rpi1) 
```

Here is the output:

```
running install
Checking .pth file support in /usr/local/lib/python3.2/dist-packages/
/usr/bin/python3 -E -c pass
TEST PASSED: /usr/local/lib/python3.2/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing python_aqbanking.egg-info/PKG-INFO
writing top-level names to python_aqbanking.egg-info/top_level.txt
writing dependency_links to python_aqbanking.egg-info/dependency_links.txt
package init file 'aqbanking/__init__.py' not found (or not a regular file)
reading manifest file 'python_aqbanking.egg-info/SOURCES.txt'
writing manifest file 'python_aqbanking.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv6l/egg
running install_lib
running build_py
running build_ext
building 'aqbanking' extension
gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -fPIC -I/usr/include/gwenhywfar4 -I/usr/include/aqbanking5 -I/usr/local/include/gwenhywfar4 -I/usr/local/include/aqbanking5 -I/usr/include/python3.2mu -c aqbanking/pyaqhandler.cpp -o build/temp.linux-armv6l-3.2/aqbanking/pyaqhandler.o -Wunused-variable -Wunused-function -std=gnu++0x
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for Ada/C/ObjC but not for C++ [enabled by default]
In file included from /usr/include/python3.2mu/Python.h:8:0,
                 from aqbanking/pyaqhandler.hpp:4,
                 from aqbanking/pyaqhandler.cpp:7:
/usr/include/python3.2mu/pyconfig.h:1182:0: warning: "_POSIX_C_SOURCE" redefined [enabled by default]
/usr/include/features.h:163:0: note: this is the location of the previous definition
/usr/include/python3.2mu/pyconfig.h:1204:0: warning: "_XOPEN_SOURCE" redefined [enabled by default]
/usr/include/features.h:165:0: note: this is the location of the previous definition
In file included from aqbanking/pyaqhandler.cpp:7:0:
aqbanking/pyaqhandler.hpp:23:26: sorry, unimplemented: non-static data member initializers
aqbanking/pyaqhandler.hpp:23:26: error: ‘constexpr’ needed for in-class initialization of static data member ‘callbackLog’ of non-integral type
aqbanking/pyaqhandler.hpp:24:31: sorry, unimplemented: non-static data member initializers
aqbanking/pyaqhandler.hpp:24:31: error: ‘constexpr’ needed for in-class initialization of static data member ‘callbackPassword’ of non-integral type
aqbanking/pyaqhandler.hpp:27:83: error: expected ‘;’ at end of member declaration
aqbanking/pyaqhandler.hpp:27:85: error: ‘override’ does not name a type
In file included from aqbanking/pyaqhandler.cpp:7:0:
aqbanking/pyaqhandler.hpp:28:150: error: expected ‘;’ at end of member declaration
aqbanking/pyaqhandler.hpp:28:152: error: ‘override’ does not name a type
aqbanking/pyaqhandler.hpp:29:85: error: expected ‘;’ at end of member declaration
aqbanking/pyaqhandler.hpp:29:87: error: ‘override’ does not name a type
aqbanking/pyaqhandler.cpp: In constructor ‘PyAqHandler::PyAqHandler()’:
aqbanking/pyaqhandler.cpp:13:8: error: ‘class PyAqHandler’ has no member named ‘callbackLog’
aqbanking/pyaqhandler.cpp:14:8: error: ‘class PyAqHandler’ has no member named ‘callbackPassword’
aqbanking/pyaqhandler.cpp: In member function ‘virtual int PyAqHandler::logHook(const char*, GWEN_LOGGER_LEVEL, const char*)’:
aqbanking/pyaqhandler.cpp:56:12: error: ‘class PyAqHandler’ has no member named ‘callbackLog’
aqbanking/pyaqhandler.cpp:62:28: error: ‘class PyAqHandler’ has no member named ‘callbackLog’
aqbanking/pyaqhandler.cpp: In member function ‘virtual int PyAqHandler::getPassword(uint32_t, const char*, const char*, const char*, char*, int, int, uint32_t)’:
aqbanking/pyaqhandler.cpp:72:12: error: ‘class PyAqHandler’ has no member named ‘callbackPassword’
aqbanking/pyaqhandler.cpp:77:37: error: ‘class PyAqHandler’ has no member named ‘callbackPassword’
aqbanking/pyaqhandler.cpp:87:39: error: ‘PyUnicode_AsUTF8’ was not declared in this scope
aqbanking/pyaqhandler.hpp: At global scope:
aqbanking/pyaqhandler.hpp:10:18: warning: ‘AqBankingInitializeError’ defined but not used [-Wunused-variable]
aqbanking/pyaqhandler.hpp:11:18: warning: ‘AqBankingDeInitializeError’ defined but not used [-Wunused-variable]
error: command 'gcc' failed with exit status 1
```

**Comment by monofox** [comment]
Hi chris(...),

for me it seems, that the `sorry, unimplemented: non-static data member initializers` is the main issue of the problems. Due to this, the variable cannot be declared and then later, the member cannot be found anymore.
This is due to the GCC. It is supported since GCC version 4.7. You're using GCC 4.6.3.

Beside of this, there is another issue: the PyUnicode_AsUTF8. According to the [python docs](https://docs.python.org/3.5/c-api/unicode.html#c.PyUnicode_AsUTF8) , this function exists only starting from Python 3.3. You're working with Python 3.2.

So right now, actually your python version is too old. But i can figure out to support also your older version of python (note: so this should be solvable easy).

So those are the points. I think, i can later look, how we can solve it, to support also your environment.

Regards,
Lukas

**Comment by monofox** [comment]
@chrissssss could you please check, if it is working for you now with this modifications?
Thanks
